import { createHash } from "node:crypto";
import {
  agentProposalSchema,
  type AgentProposal,
  type FabricAgentId,
} from "@atlas/shared";

/**
 * STUB GENERATOR — NOT A REAL LLM CALL SITE.
 *
 * There is no fabric-agent LLM call site in this codebase yet that emits an
 * `AgentProposal` (the only two real LLM call sites today are
 * `apps/api/src/routes/agent.ts` and `apps/api/src/routes/conversation.ts`,
 * neither of which produces this shape). This generator exists SOLELY so
 * the full proposal pipeline — generate proposal → validate → dispatch-gate
 * → audit — can be proven end-to-end in tests without a real LLM/API key.
 *
 * It is deliberately deterministic: identical input always produces an
 * identical `AgentProposal` (no randomness, no network call, no wall-clock
 * read baked into the output beyond a fixed constant), so tests built on it
 * stay reproducible. The emitted evidence is tagged `authorityRank:
 * "LLM_INFERENCE"` (the lowest-authority rank in `SOURCE_AUTHORITY_RANKS`)
 * and `epistemicState: "PROPOSED"` — an honest label, never dressed up as
 * "OBSERVED" or "VERIFIED" fact.
 *
 * DO NOT wire this into any real request path. When Phase 1 adds real
 * LLM-backed fabric-agent calls, replace call sites of this function with a
 * generator that derives `claims` / `evidence` / `confidence` / `rationale`
 * from an actual model response, and delete this stub.
 */
export interface StubAgentProposalInput {
  readonly agentId: FabricAgentId;
  readonly taskId: string;
  readonly projectId: string | null;
  /** Owner of the deterministic stub evidence this generator fabricates — must be a real caller-supplied id, never invented here. */
  readonly ownerId: string;
  readonly entityType: string;
  readonly action: string;
  readonly inputs?: Record<string, unknown>;
}

/** Fixed instant used for all stub evidence timestamps, so output stays byte-for-byte deterministic across runs. */
const STUB_OBSERVED_AT = "2026-01-01T00:00:00.000Z";

/**
 * Deterministically derives a syntactically-valid UUID (v4 shape) from a
 * seed string via SHA-256 — no `crypto.randomUUID()` here, since the whole
 * point of this generator is reproducible output for a fixed input.
 */
function deterministicUuid(seed: string): string {
  const hex = createHash("sha256").update(seed).digest("hex").slice(0, 32).split("");
  hex[12] = "4"; // version nibble
  const variantSource = hex[16] ?? "0";
  hex[16] = ((parseInt(variantSource, 16) & 0x3) | 0x8).toString(16); // variant nibble
  const joined = hex.join("");
  return [
    joined.slice(0, 8),
    joined.slice(8, 12),
    joined.slice(12, 16),
    joined.slice(16, 20),
    joined.slice(20, 32),
  ].join("-");
}

/** Generates a schema-valid, deterministic `AgentProposal` — see module doc comment for why this stub exists and its replacement plan. */
export function generateStubAgentProposal(
  input: StubAgentProposalInput,
): AgentProposal {
  const evidenceId = deterministicUuid(`${input.taskId}:agent-proposal-stub:evidence:0`);

  return agentProposalSchema.parse({
    agentId: input.agentId,
    taskId: input.taskId,
    projectId: input.projectId,
    action: { entityType: input.entityType, action: input.action },
    inputs: input.inputs ?? {},
    claims: [
      `[STUB] ${input.agentId} proposes ${input.action} on ${input.entityType} for task ${input.taskId}`,
    ],
    evidence: [
      {
        id: evidenceId,
        ownerId: input.ownerId,
        projectId: input.projectId,
        source: "agent-proposal-stub-generator",
        sourceType: "SYSTEM",
        sourceId: input.taskId,
        uri: null,
        excerpt:
          "Deterministic stub evidence — fabricated by agent-proposal-stub-generator.ts to prove pipeline wiring, not a real observation.",
        version: null,
        observedAt: STUB_OBSERVED_AT,
        createdAt: STUB_OBSERVED_AT,
        confidence: 0.5,
        epistemicState: "PROPOSED",
        category: "TASKS",
        classification: "INTERNAL",
        authorityRank: "LLM_INFERENCE",
        metadata: { stub: true },
      },
    ],
    confidence: 0.5,
    rationale: `[STUB] Deterministic rationale for ${input.agentId} task ${input.taskId} — generated by agent-proposal-stub-generator.ts, NOT a real LLM. Replace with a real LLM-backed proposal generator when Phase 1 wires actual LLM calls to fabric agents.`,
  });
}
